/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "wrappers.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_protobuf_DoubleValue, google_protobuf_DoubleValue, AUTO)


PB_BIND(google_protobuf_FloatValue, google_protobuf_FloatValue, AUTO)


PB_BIND(google_protobuf_Int64Value, google_protobuf_Int64Value, AUTO)


PB_BIND(google_protobuf_UInt64Value, google_protobuf_UInt64Value, AUTO)


PB_BIND(google_protobuf_Int32Value, google_protobuf_Int32Value, AUTO)


PB_BIND(google_protobuf_UInt32Value, google_protobuf_UInt32Value, AUTO)


PB_BIND(google_protobuf_BoolValue, google_protobuf_BoolValue, AUTO)


PB_BIND(google_protobuf_StringValue, google_protobuf_StringValue, AUTO)


PB_BIND(google_protobuf_BytesValue, google_protobuf_BytesValue, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

